### ISSUE TITLE
Error: the special identifier '_' is ignored in declarations and cannot be used

### ISSUE THREAD

**Issue by bung87** [treeform/windy#105]
I see windy use a lot in function declaration as argument. it's CT error in nim devel

nim version: Nim Compiler Version 1.9.5 [MacOSX: amd64]

**Comment by kunitoki** [comment]
Yeah getting this on mac since upgrading to nim 2.0.0, can the PR be merged ?

**Comment by Auratelience** [comment]
getting this issue as well on macos

**Comment by guzba** [comment]
Fixed in https://github.com/treeform/windy/pull/112
