### ISSUE TITLE
Why does Windy deal with HTTP requests and websockets?

### ISSUE THREAD

**Issue by radekm** [treeform/windy#115]
Hi,

I'm just curious why does Windy provide HTTP functionality?

It seems that Windy is about making and managing windows on different
platforms and HTTP seems like different topic. Is there a reason
why does Windy also include HTTP support?

**Comment by guzba** [comment]
Using OS provided HTTP is the vastly better option vs Nim's HTTP on both Windows and Mac. You don't need to use the APIsi fyou do not want to.
