### ISSUE TITLE
Error creating opengl 2.0 ES context

### ISSUE THREAD

**Issue by creikey** [treeform/windy#42]
```nim
import opengl, os, windy

when isMainModule:

  let window = newWindow(
    "Windy",
    ivec2(1280, 800),
    openglMajorVersion = 2,
    openglMinorVersion = 0,
  )

  window.makeContextCurrent()
  loadExtensions()

  echo "GL_VERSION: ", cast[cstring](glGetString(GL_VERSION))
  echo "GL_VENDOR: ", cast[cstring](glGetString(GL_VENDOR))
  echo "GL_RENDERER: ", cast[cstring](glGetString(GL_RENDERER))

  while not window.closeRequested:
    pollEvents()
    sleep(10)
```

Error:
```
C:\Users\Cameron\Documents\Authored\nimzoom\src\nimzoom.nim(5) nimzoom
C:\Users\Cameron\.nimble\pkgs\windy-0.0.0\windy\platforms\win32\platform.nim(895) newWindow
[[reraised from:
C:\Users\Cameron\Documents\Authored\nimzoom\src\nimzoom.nim(5) nimzoom
C:\Users\Cameron\.nimble\pkgs\windy-0.0.0\windy\platforms\win32\platform.nim(911) newWindow
]]
Error: unhandled exception: Error creating OpenGL context [WindyError]
```

**Comment by treeform** [comment]
You can't just open openGL 2.0 ES context on windows, you have to install some thing else. There are several options see: https://stackoverflow.com/questions/1446461/getting-started-with-opengl-es-2-0-on-windows. I don't think windy will support ancient open GL versions. I bet it requires extra things and hookups.

Note "openGL 2.0 ES" (publicly released in 2007) is not same thing as just "openGL 2.0" (released in 2004). You might be able to get windows to give you plain openGL 2 with some effort but I never tried.  We only test with OpenGL 4 (released in 2010) and above. Pretty much all hardware supports OpenGL 4. 

Why do you need openGL 2.0 ES?

**Comment by creikey** [comment]
@treeform honestly just because godot has a GLES2 renderer I've seen running pretty much everywhere, as it's the same thing as webgl 1 (webgl 2 has issues with safari and old iphones iirc), and I only need some 2d graphics and many different shaders (such as sdf font rendering). For my purposes anyways with windy I think it might be better to have a separate implementation for the web anyways where it uses the nim js target and targets a canvas on the webpage with webgl 2 which is compatible with ES3

**Comment by treeform** [comment]
Sorry, we though about this and we will not support GLES2 for now. We might do so in the future.

I will close the ticket for now.
