### ISSUE TITLE
mouseDelta incorrectly accumulates on windows

### ISSUE THREAD

**Issue by creikey** [treeform/windy#49]
Not sure if this exists on other platforms
```nim
import opengl, windy

let window = newWindow("Windy Basic", ivec2(1280, 800))

window.makeContextCurrent()
loadExtensions()

var offset = ivec2(0, 0)

proc display() =
  glClear(GL_COLOR_BUFFER_BIT)
  # Your OpenGL display code here
  window.swapBuffers()

while not window.closeRequested:
  display()
  pollEvents()
  if window.buttonDown[MouseLeft]:
    offset += window.mouseDelta
  echo offset
```

Run this, then click and drag the mouse starting in the upper left corner and move it around for ~20 seconds, when you bring the mouse back to the starting point (while still dragging) the offset will be wrong by a magnitude of about 100

Video demonstration:

https://user-images.githubusercontent.com/28424206/149639175-2427a23b-58c2-438c-844f-31073179b100.mp4

**Comment by treeform** [comment]
Thank you for the bug report. I think we fixed it. Feel free to reopen if it still does not work for you.
