### ISSUE TITLE
mousePrevPos set to zero when mouse not moving on Windows

### ISSUE THREAD

**Issue by creikey** [treeform/windy#51]
From this program:
```nim
import opengl, windy

let window = newWindow("Windy Basic", ivec2(1280, 800))

window.makeContextCurrent()
loadExtensions()

proc display() =
  glClear(GL_COLOR_BUFFER_BIT)
  # Your OpenGL display code here
  window.swapBuffers()

while not window.closeRequested:
  display()
  pollEvents()
  echo window.mousePrevPos

```

![image](https://user-images.githubusercontent.com/28424206/149643578-44a448d7-445b-4505-a782-866371b576ed.png)

**Comment by treeform** [comment]
Thank you for the bug report. I think we fixed it. Feel free to reopen if it still does not work for you.

**Comment by creikey** [comment]
> Thank you for the bug report. I think we fixed it. Feel free to reopen if it still does not work for you.

Just tested the latest update, issue is gone. Thanks for this library, it's really nice to use
