### ISSUE TITLE
Compiler error without feature turned on

### ISSUE THREAD

**Issue by creikey** [treeform/windy#72]
```
win32\platform.nim(1348, 12) Error: startHttpRequest requires --threads:on option
```
Not sure if this can be configured per nimble library that it needs this feature to be used?

**Comment by guzba** [comment]
Hm, I guess that approach isn't going to work. Instead I'll just not include the code without --threads:on until I can ideally remove the requirement (have idea but not guaranteed).

Added to this PR:

https://github.com/treeform/windy/pull/71

**Comment by guzba** [comment]
This should be fixed now.
